stages:
  - build

.build_job:
  stage: build
  before_script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
  after_script:
    - docker image prune -a -f
  tags:
    - hz-afs

build_dev:
  extends: .build_job
  script:
    - docker build --no-cache -t $CI_REGISTRY_IMAGE:dev .
    - docker push $CI_REGISTRY_IMAGE:dev
  only:
    - master

build_tag:
  extends: .build_job
  script:
    - docker build --no-cache -t $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG .
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG
  only:
    - tags

build_branch:
  extends: .build_job
  script:
    - docker build --no-cache -t $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME .
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME
  except:
    - master
    - tags
