name:                imps
version:             0.1.0.0
github:              "githubuser/imps"
license:             BSD3
author:              "Aleksey Danilevsky"
maintainer:          "alexey.danilevsky@gmail.com"
copyright:           "2020 Aleksey Danilevsky"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/imps#readme>

dependencies:
- base >= 4.7 && < 5
- bytestring
- gd
- hsexif
- http-types
- scotty
- text

library:
  source-dirs: src

executables:
  imps:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - imps

tests:
  imps-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - imps
